# ntk-manifest-artifact.yml — Single artifact add/update
apiVersion: ntk/v1
kind: solution

meta: { name: Rent.Service }

conventions:
  namespaceRoot: Rent.Service
  targetFramework: net9.0
  policy: { collision: fail, insertTodoWhenMissing: true, strict: true }

solution: { root: samples/src, slnFile: Rent.Service.sln }

guards:
  requireExistingProjects: true
  onMissingProject: fail

projects:
  Domain: { type: domain, name: Rent.Service.Domain, path: Rent.Service.Domain }

contexts:
  - name: Rentals
    aggregates:
      - name: Rental
        entities:
          - name: Rental
            fields: [ { name: Id, type: Guid, key: true } ]

templates:
  mapping:
  - { artifact: entity, template: dotnet/domain/entity.hbs, dst: "samples/src/Rent.Service.Domain/Entities/{Name}.cs" }

render:
  rules:
    - { expand: "contexts[*].aggregates[*].entities[?name=='Rental']", as: entity }

apply:
  mode: artifact
  artifact:
    kind: entity
    context: Rentals
    name: Rental
